### PR TITLE
new top level for rpi-imager

### PR DESCRIPTION
**Pull request by georgejhunt**
Tim could you merge this PR and update the http://iiab.me top level menu json to reflect the new downloads. Thanks

### CODE REVIEW

**Comment by tim-moody** [comment]
I'd like '(formerly raspbian)' added to the descriptions

**Comment by georgejhunt** [comment]
It might help me to understand what you want if you suggested what
line the the top level program you wanted to change.

See https://github.com/iiab/iiab-factory/blob/master/box/rpi/iiab-imager/top_level.py

If you are suggesting that we start rewriting their menu items, I
think that is a bad idea.

**Comment by tim-moody** [comment]
My comment was not about top_level.py and I was not aware that they had changed the menu items. I thought that was us. The only file changed by this PR is the json file, but maybe that is an extraction from their json file.

**Comment by georgejhunt** [comment]
On Fri, Jun 12, 2020 at 1:37 PM Tim Moody <notifications@github.com> wrote:
>
> My comment was not about top_level.py and I was not aware that they had changed the menu items. I thought that was us. The only file changed by this PR is the json file, but maybe that is an extraction from their json file.
top_level.py does the extraction

**Comment by tim-moody** [comment]
the new file is in place on iiab.me

**Pull request merged**
