### PR TITLE
rework upload.py

### PR DESCRIPTION
**Pull request by georgejhunt**
I did a lot of work on upload that was never transferred from my repo to iiab. It is still pretty raw. I'll need to use it more to iron out the bugs.

### CODE REVIEW

**Comment by holta** [comment]
Thanks @georgejhunt

(Any quick clarifications appropriate for https://github.com/iiab/iiab-factory/blob/master/box/rpi/iiab-imager/README.md — helping others get to know upload.py or its purpose ?)

**Comment by holta** [comment]
Looks great.  Thanks @georgejhunt for this and also for PR #114

**Comment by tim-moody** [comment]
I know that for the internetarchive cli utility you have to record your password token. Is that necessary here and if so how is it done?

**Comment by georgejhunt** [comment]
It's been a while since I set it up. I think there's a hidden file in
the home (/root/.ia) directory which has a software key. I think the
same credentials work for cli as well as the python api.

**Pull request merged**
