### PR TITLE
Subset osm

### PR DESCRIPTION
**Pull request by georgejhunt**

### CODE REVIEW

**Comment by tim-moody** [comment]
can we use  /library/working (or downloads or a combination)/osm/<subset_name/output instead of  /library/<subset_name/output

**Comment by georgejhunt** [comment]
good idea

**Comment by tim-moody** [comment]
shall we give this a whirl on hadron?

**Comment by georgejhunt** [comment]
This might fail on hadron -- since the script assumes that
/library/knowledge exist, and that the source is in our normal place.

I think I should soft code more stuff, and then verify that I was
successful on hadron.

**Pull request merged**
