### PR TITLE
add kernel warning for RaspOS

### PR DESCRIPTION
**Pull request by jvonau**
https://github.com/iiab/iiab/issues/2497

### CODE REVIEW

**Comment by jvonau** [comment]
@holta

**Comment by holta** [comment]
Is kernel >= #1336 presumably required on all hardware {RPi 3, RPi 3 B+, RPi 4} and both flavors of RaspiOS {32-bit, 64-bit} ?

**Comment by jvonau** [comment]
I'll go with same kernel source code compiled at the same time for 4 kernels should have similar results on similar hardware, you can test accessing the hotspot on RaspOS-arm64 with the latest apt 1333 kernel.

**Comment by holta** [comment]
@jvonau if poss can this PR by sync'd up with https://github.com/jvonau/iiab-factory/blob/jv-pi-gen/iiab#L269-L286 so I/others can test it in its final form?

**Pull request closed without merging**
