### PR TITLE
Release

### PR DESCRIPTION
**Pull request by georgejhunt**
Add released desktop IIAB 7.1, remove pre-released version.

### CODE REVIEW

**Comment by tim-moody** [comment]
I'm not clear why the various sizes were changed from string to number. The string version works with rpi-imager; haven't tested the number version.

**Comment by holta** [comment]
> I'm not clear why the various sizes were changed from string to number. The string version works with rpi-imager; haven't tested the number version.

Interesting...thanks @georgejhunt if you can clarify...perhaps both string & number are ok?

**Comment by georgejhunt** [comment]
I was attempting  to correct the overlap and the lack of proper spacing on the menu items. Also the size was displayed as 0GB, which is corrected when size items are numbers.

**Comment by tim-moody** [comment]
OK. I have changed my script as well.

**Pull request merged**
