### PR TITLE
1-line installer options to (1) use {{ iiab_admin_user }} instead of iiab-admin (2) not create the admin user [and password implementation discussion]

### PR DESCRIPTION
**Pull request by holta**
Heavily tested on RaspiOS; lightly tested on Ubuntu 20.04.1

Refs:
- iiab/iiab#2561, PR iiab/iiab#2566, PR iiab/iiab#2570
- iiab/iiab-admin-console#345, PR iiab/iiab-admin-console#346, PR iiab/iiab-admin-console#347, PR iiab/iiab-admin-console#348
- PR #132, PR #151

### CODE REVIEW

**Comment by tim-moody** [comment]
so now it uses iiab_admin_user but doesn't use iiab_admin_published_pwd or iiab_admin_pwd_hash

**Comment by holta** [comment]
> so now it uses iiab_admin_user but doesn't use iiab_admin_published_pwd or iiab_admin_pwd_hash

bash doesn't need {{ iiab_admin_pwd_hash }} as it can change the password directly (unlike Ansible apparently!) based on an actual password string or variable like {{ iiab_admin_published_pwd }}.

Yesterday I added {{ iiab_admin_published_pwd }} to the 1-line installer code similar to your suggestion.  Earlier today I removed that, as it's more of a constant than a variable, e.g. things that change every-decade-or-so tend to clutter up code understandability.

But I can add that back in if someone is planning on changing `g0adm1n` in the coming year or so?  (i.e. looking back over our past decade and our future decade, thousands of other things will also change, so I prefer to avoid softcoding things make code less readable, and materially _less maintainable_.  Extreme example just to illustrate the point: softcoding `/etc` is taking things way too far in my opinion, as it makes code less understandable for something that will realistically never change.  But in this case, if `g0adm1n` will realistically be changing in the coming year or two, that's a valid concern and I'll take that into account.)

**Comment by tim-moody** [comment]
so if I changed  iiab_admin_user to pi in local vars, this script would change pi's password to g0adm1n regardless of what I put in iiab_admin_published_pwd ? 

also, the title says 2) not create the admin user, but under the right conditions does useradd "$IIAB_ADMIN_USER" which confuses me.

**Comment by holta** [comment]
> so if I changed iiab_admin_user to pi in local vars, this script would change pi's password to g0adm1n regardless of what I put in iiab_admin_published_pwd ?

Intentionally: I don't think we want to encourage plaintext passwords of admin users in local_vars.yml — this is dangerous.

But if {{ iiab_admin_published_pwd }} (not a user-facing variable, but a long-term constant, which is why `published` is in its name) will be changed by maintainers in the coming year or two — and if so a huge amount of work changing the many dozens of associated documentation/support resources alongside, as well as community habits which takes years to change in the wider culture — then this begins to become a pragmatic question.

i.e. if that's really advisable, one could imagine bypassing Ansible's hash approach entirely in future — rewriting roles/iiab-admin/tasks/admin-user.yml to call out to bash's `chpasswd` if such is necessary?

...whether or not we later chose to deprecate {{ iiab_admin_pwd_hash }} if it's decided this risks too much confusion when/if it directly conflicts with {{ iiab_admin_published_pwd }}.

Then again, changing passwords using Ansible might just be a bad idea almost across-the-board...

In Any Case: does anyone know if `g0adm1n` dates back to OLPC XS days possibly, and if so might it be approaching its 14th birthday in early 2021??

> also, the title says 2) not create the admin user, but under the right conditions does useradd "$IIAB_ADMIN_USER" which confuses me.

CLARIF: this ticket title/subject says "options to...not create admin user" which is referring to setting variable `iiab_admin_user_intall: False` which I think @jvonau established about 3-4 years ago.

**Comment by holta** [comment]
On the negative side:
- I don't know if we or anyone really wants to modify {{ iiab_admin_pwd_hash }} regularly &mdash; as a truly practical matter.
- It's far from optimal security to encode your (non-`g0adm1n`) customized password's hash and salt like this, into a file (local_vars.yml) readable by all Linux users.

On the positive side:
- If we discover a community of people that honestly and truly want to do this regularly (encode their iiab-admin password into local_vars.yml, as boneheaded as that might be ;) then it can certainly be added to the 1-line installer if this is determined to be genuinely necessary ??

**Comment by tim-moody** [comment]
>But if {{ iiab_admin_published_pwd }} (not a user-facing variable, but a long-term constant,

where is it used? if nowhere then maybe eliminate it. seems hard coded in sshpwd-profile-iiab.sh

I invented g0adm1n. Don't remember when, but early days of admin console.

>It's far from optimal security to encode your (non-g0adm1n) customized password's hash and salt like this, into a file (local_vars.yml) readable by all Linux users.

The point of using a hash is to avoid having the password in plaintext. It is the recommended means of providing security, as hashing is a one way function.

**Comment by tim-moody** [comment]
> where is it used? if nowhere then maybe eliminate it. seems hard coded in sshpwd-profile-iiab.sh

I guess I was looking at an old version as I see it there now.

**Comment by holta** [comment]
> > But if {{ iiab_admin_published_pwd }} (not a user-facing variable, but a long-term constant,
> 
> where is it used? if nowhere then maybe eliminate it. seems hard coded in sshpwd-profile-iiab.sh

Good question.  Also it's in [sshpwd-lxde-iiab.sh](https://github.com/iiab/iiab/blob/master/roles/iiab-admin/templates/sshpwd-lxde-iiab.sh) to likewise warn implementers when they're endangering themselves.

Ambiguous yes, but as a global constant, this still serves a potentially valuable purpose in my opinion, as the idea of `g0adm1n` crops up in so many places &mdash; and not just in code &dash; as this notion (if not `g0adm1n` itself) appears nearly constantly in documentation.

Now I'm thinking that {{ iiab_admin_published_pwd }} possibly really should be restored into the 1-line installer here (reversing myself for the 2nd time in 24h!) to be consistent, hmm.  That is f I try to minimize the code bloat (so it remains approachable for IIAB/bash newbies).

> I invented g0adm1n. Don't remember when, but early days of admin console.

Seems likely to be useful for many more years, and for very good reason if so &mdash; easy to communicate by phone etc, when it's needed most &mdash; during community onramping / support situations / etc.

> > It's far from optimal security to encode your (non-g0adm1n) customized password's hash and salt like this, into a file (local_vars.yml) readable by all Linux users.
> 
> The point of using a hash is to avoid having the password in plaintext. It is the recommended means of providing security, as hashing is a one way function.

Back in the day.  In recent years `/etc/shadow` is carefully hidden from non-root users, as publishing the salt used to hash your administrative password asking for trouble (certainly not without risk). Particularly as these "offline" systems keep creeping back online more and more, even before affordable "Starlink" connections arrive to remote/desolate communities worldwide in coming years~

Personally I'm not seeing much/anything to gain by advertising {{ iiab_admin_pwd_hash }} as a (supposed, extremely painful to use!) "feature" &mdash; and plenty to lose.  Paid in terms of ongoing complexity and community confusion/opaqueness around the whole frustrating notion &mdash; anyway in my opinion this community invitation to hash IIAB's main admin password is a bad idea still going nowhere years later &mdash; and if so a possibly candidate for deprecation someday soon?

However: if there emerges a field community that truly needs a fixed password provisioned for `iiab-admin` etc, e.g. across an enterprise (with all the many dangers that entails) then I suppose all this hashing bureaucracy could be more than theoretical, _with a slim purpose?_  (In which case they really should talk to us about their specific needs...and also ask about our enterprise rates ;-)

**Comment by tim-moody** [comment]
>publishing the salt used to hash your administrative password is asking for trouble

to the contrary having a salt makes it more secure even if visible; it prevents a single rainbow table from serving all passwords. passwords are protected by math, not obfuscation. without a salt you can compute all possible passwords and their corresponding hash and then look a given hash up in the table to decode it. with salt you have to compute such a table for every salt, which is not computationally feasible in a reasonable amount of time https://security.stackexchange.com/questions/118513/how-long-will-it-take-to-break-a-salted-password#:~:text=Now%20you%20can%20test%2064,150k%20years%20per%20distinct%20salt.

**Comment by tim-moody** [comment]
OK. Maybe I'm overly optimistic https://stackoverflow.com/questions/6776050/how-long-to-brute-force-a-salted-sha-512-hash-salt-provided if the password is not random.

**Comment by holta** [comment]
I added further softcoding of `{{ iiab_admin_user }}` & `{{ iiab_admin_published_pwd }}` not because I believe it's all that wise here, but just in case this (might, hopefully!) offer maintainability benefits here in future years?  Even despite this causing bash bloat making the 1-line installer harder for newcomers to read/parse/understand :/

Aside: an excess of softcoding is never desirable (prematurely overgeneralizing, etc) but in this case that probably applies even in future when we might be able to read Ansible vars from bash etc in a more automatic/universal/validated way.  In my opinion anyway.  One Reason: the UX very intentionally confronts the implementer at The Very 1st Moment after they run the 1-line installer, before default_vars.yml and local_vars.yml even yet exist &mdash; so to get them comfortable (immediately) with 2 topmost priorities:

1. The need for an account like 'iiab-admin' so they can use Admin Console after IIAB is installed.
2. We also ask them to change password(s) for 'pi' and/or 'iiab-admin' (auto-populated if local_vars.yml already in place).

I consider those 2 much more important than familiarizing them with local_vars.yml and apt security updates etc.  But all these human explanations ("IIAB best practices, tips & tricks") are very subtle cultural questions for sure, that can and should be improved in future whenever newcomer experience(s) can be materially catalyzed, possibly even translated into other languages in future if that's what people truly want...?

**Comment by holta** [comment]
Re-tested in a variety of situations on RaspiOS.

**Comment by holta** [comment]
FYI this PR intentionally highlights this public page and README during the 1-line install process — summarizing some important ongoing IIAB security design/choices — e.g. relating to iiab-admin's current requirement that it be a member of the sudo group etc:

https://github.com/iiab/iiab/tree/master/roles/iiab-admin

**Pull request merged**
