### PR TITLE
Still want to update just don't ask

### PR DESCRIPTION
**Pull request by jvonau**
Still want to update just don't ask

### CODE REVIEW

**Comment by holta** [comment]
The counterargument is that `apt update` and `apt -y dist-upgrade` commands are so slow, that they're (sometimes/often) not desired during testing.

**Comment by jvonau** [comment]
I'll agree if you run `apt update` and `apt upgrade` sometime prior to installing, but in the interests of starting off everybody at the same base starting point moving forward, might save a bit of unforeseeable grief down the road. Still want to build in little steps and fail early if something is not quite right. Remember the idea is if things should want to fail show that ugly side early, might catch unclean updates of the underling OS that missed QA and we don't want to blame scripts/ansible as the next touch point of execution.

**Comment by holta** [comment]
> in the interests of starting off everybody at the same base starting point

I agree but that requires a reboot.

I wish it was easy to reboot on kernel updates only.  Then again there's almost a kernel update within (about) a week of almost every OS's release, so this feels like a classic case of over-optimizing.

I'll try a different approach, that:

1. Forces a reboot but asks less questions.
2. Requires less typing by using http://d.iiab.io/test.txt for those rare people who dedicate their time to thoughtful testing.

**Comment by holta** [comment]
> I'll try a different approach, that:
> 
> 1. Forces a reboot but asks less questions.
> 2. Requires less typing by using http://d.iiab.io/test.txt for those rare people who dedicate their time to thoughtful testing.

Clueless citizens (who will never read instructions) impose high costs on others.

Still &emdash; I'm modifying by suggestion in favor of dedicated souls (who actually exert energy to communicate, test & assist others thoughtfully) as follows:

http://d.iiab.io/fast.txt

As per:

- PR #182

**Comment by jvonau** [comment]
> > in the interests of starting off everybody at the same base starting point
> 
> I agree but that requires a reboot.
>

Yes the fly in the soup is RasPiOS, their packaging only allows one kernel version at a time if I recall correctly. Could try running apt upgrade later, after the kalite stuff, in place of being first and hitting a kernel update out of the gate forcing the reboot?

> I wish it was easy to reboot on kernel updates only. Then again there's almost a kernel update within (about) a week of almost every OS's release, so this feels like a classic case of over-optimizing.

The thing is with building images you are not running the packaged kernel, just installing another file so no reboot is required. The reboot is really an RasPiOS issue and the docs state that a fully updated and rebooted system should be the starting point, I'm a bit torn but --fast should be fine for my use case.

**Pull request closed without merging**
