### PR TITLE
add desktop preview 2 to imager

### PR DESCRIPTION
**Pull request by georgejhunt**
I'd like to pull this into master to verify that copying the json file from my test branch to master is all it takes publish a new image

### CODE REVIEW

**Comment by tim-moody** [comment]
how do images get out of this system? how many should be in the imager menu at a given time?

**Comment by georgejhunt** [comment]
I think just the current released version (3-4 items) should be the max.

**Comment by tim-moody** [comment]
name is a little funny /200408-raspbian-desktop-med-preview2-gc0f79ec--.img.zip",

**Comment by georgejhunt** [comment]
Yes, I've put in a check in my version of min_sd to exit with a
message if factory.settings is missing. But the check was not in place
when I created it

**Pull request merged**
