### PR TITLE
Double reserve disk to 2%; act on admin_console_install and _enabled

### PR DESCRIPTION
**Pull request by holta**
1) Doubles the reserve disk space from 1% to 2% [*]  to extend the life of microSD cards, particularly now that large capacity cards are so much cheaper since ~2019.

   [*] tune2fs default is 5%.  IIAB has defaulted to 1% since Aug 2017 for field communities tying to eke out every last gigabyte for content.

2) `admin_console_install` and `admin_console_enabled` variables (that were set up about a year ago) are now finally acted upon.

Tested on Debian 10.6

### CODE REVIEW

**Comment by holta** [comment]
systemd's enabling/disabling and starting/stopping of [iiab-cmdsrv.service](https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/templates/iiab-cmdsrv.service.j2) can be enhanced and/or supplemented with NGINX logic later, as necessary.

**Comment by tim-moody** [comment]
There are a number of problems with this PR:

1. anyone with admin console already installed will never get updates
2. there will be contention in that anyone running iiab-admin-console/install will turn cmdsrv back on and then iiab-install will turn it off again
3. local vars was not intended to be used outside of ansible.
4. the comment that admin console installs js-menu is not entirely accurate as there is a js-menu_install variable that controls whether js-menu is installed or not.

**Comment by holta** [comment]
> 1. anyone with admin console already installed will never get updates

This PR doesn't affect whether or not Admin Console gets updates.

I suspect @tim-moody is talking about `/etc/iiab/install-flags/iiab-admin-console-complete` that @jvonau implemented around early 2020.

Which is indeed an interesting question.

My opinion is that 'sudo iiab' wasn't intended to be run after initial install of IIAB, so the behavior that @jvonau proposed and was implemented then ( i.e. around early 2020, the various install flags placed in `/etc/iiab/install-flags/` ) seemed fair...or at least seemed good enough.

> 2. there will be contention in that anyone running iiab-admin-console/install will turn cmdsrv back on and then iiab-install will turn it off again

I haven't seen any enabling/disabling contention during my many tests.

But will help fixing them if they exist, if others can help shed light?

(Just as an aside, I don't expect many will want to disable Admin Console.  A number even far fewer than those who won't want to install Admin Console.)

> 3. local vars was not intended to be used outside of ansible.

Best of intentions yes: thanks to David Farming's dedication and others who've put their lives into trying to eke the most out of Ansible, for sure.

But after 7 years Ansible remains a "pig" and as such there are a number of cases like firmware, openvpn (and possibly network?) where avoiding Ansible became increasingly necessary — as judiciously as possible and while respecting the implementer's wishes in `/etc/iiab/local_vars.yml`

> 4. the comment that admin console installs js-menu is not entirely accurate as there is a js-menu_install variable that controls whether js-menu is installed or not.

Good to know.

Where is that comment?  (Are you talking about the following comment from a couple years ago?)

https://github.com/iiab/iiab/blob/master/vars/default_vars.yml#L75-L77

**Comment by holta** [comment]
> `/etc/iiab/install-flags/iiab-admin-console-complete` that @jvonau implemented around early 2020.

CLARIF, it was a bit earlier than I remembered — @jvonau's commit was from over a year ago here: https://github.com/iiab/iiab-factory/pull/79/commits/60f6dec51525ec810ea6073b7c0e2d0b7ad7d58e

**Comment by jvonau** [comment]
> There are a number of problems with this PR:
> 
>     1. anyone with admin console already installed will never get updates
> 

Nor iiab by design, it's an **installer** script, you have to have some sort of finish line to cross and an auto reboot at the end is not enough info on if it was successful or not.

>     2. there will be contention in that anyone running iiab-admin-console/install will turn cmdsrv back on and then iiab-install will turn it off again

Sorry iiab-install and thus iiab (the repo) doesn't contain any cmdsrv logic, if you are suggesting 'iiab' (the script) has that behavior I would agree. Think the main aim is(no clue this caught me by off guard also):

1. Turn off the installation of admin console all together
Using some feedback from https://github.com/iiab/iiab/issues/1737 as a deployment example I could see a wish to exclude the console if the intent is to deploy a _single_ CMS as the flagship for that deployment. I'd change the iiab_home_url to point to the single CMS and omit admin-console using 'the do it by hand approach', is looks to be a better defined extension of that train of thought.

2. To be able to turn cmdsrv off post content curation/pre-deployment image creation by editing *_enabled local_vars.yml and running 'sudo iiab' if place of doing `sudo systemctl disable iiab-cmdsrv` 

The flaw I see is there no user input validation once iiab-install completes, think that can be addressed with check-vars from  https://github.com/iiab/iiab/pull/2539 called from `sudo iiab`

> 
>     3. local vars was not intended to be used outside of ansible.
>

I was assuming that admin-console was always installed, but there were on and off issues with ka-lite portion of the install later on, the flags help to recover the install faster without repeating all the steps.

What is the alternative with the split git repos then? Have admin_console exit if local_vars.yml has install false?

> > `/etc/iiab/install-flags/iiab-admin-console-complete` that @jvonau implemented around early 2020.
> 
> CLARIF, it was a bit earlier than I remembered — @jvonau's commit was from over a year ago here: [60f6dec](https://github.com/iiab/iiab-factory/commit/60f6dec51525ec810ea6073b7c0e2d0b7ad7d58e)

The lineage of PRs start Jul 25, 2018 #33,with #73 #77 #78 #79 being updates revisions

**Comment by tim-moody** [comment]
Another useless argument. nolo contendere

**Comment by jvonau** [comment]
Just so I fully understand,the issues
1 PR pushed without advanced warning 
2 there was an objection to this PR raised, 
3 question was asked to shed some light
4 validation point raised
5 question was asked for an alternative
Thought there was a "what can be better" discussion starting, but I guess I was mistaken.

**Comment by tim-moody** [comment]
don't think we're converging on anything useful.

**Pull request merged**
