### PR TITLE
'sudo iiab --fast' for clueful ppl dedicated to testing

### PR DESCRIPTION
**Pull request by holta**
Related:

- PR #179 
- PR #180
- PR #181

### CODE REVIEW

**Comment by holta** [comment]
In summary, this PR is to support dedicated people (who actually exert energy to communicate and assist others thoughtfully with quality engineering / quality assurance, rather than just talking about it ;) as follows:

Kick off a "fast" IIAB install with any of these...

- `curl http://d.iiab.io/fast.txt | sudo bash`
- `curl http://d.iiab.io/fast.txt | sudo bash -s -f`
- `curl http://d.iiab.io/fast.txt | sudo bash -s --fast`

Continue any "fast" install (e.g. after a mandatory reboot to a new kernel etc) with either of these...

- `sudo iiab -f`
- `sudo iiab --fast`

**Comment by holta** [comment]
Aside...if you truly want to move-fast-and-break-things (MFABT) this even more aggressive option is also available...if you want to avoid `apt` (for OS updates, new kernel, reboot) completely:

```curl d.iiab.io/install.txt | sudo bash -s mfabt```

Followed by...

```sudo iiab --mfabt```

**Comment by holta** [comment]
In sum, it's a bit like {S, M, L} T-shirt sizes &mdash; giving folks 3 options:

1) NORMAL IIAB installs educate the implementer on important topics:
`curl d.iiab.io/install.txt | sudo bash`
If interrupted, continue with...
`sudo bash`

2) "Fast" installs, for Dedicated Testing Peops especially:
`curl d.iiab.io/fast.txt | sudo bash`
If interrupted, continue with...
`sudo bash -f`

3) Move-Fast-and-Break-Things installs, for Devs especially:
`curl d.iiab.io/install.txt | sudo bash -s --mfabt`
If interrupted, continue with...
`sudo bash -mfabt`

**Comment by georgejhunt** [comment]
I like --fast. Thanks

**Comment by jvonau** [comment]
Let's not roll back security as was alluded to in https://github.com/iiab/iiab-factory/pull/178#issuecomment-901278908. I see --fast is a straight knockoff of my 50ddbb632b4ca3b011b179e41a7c700d9c76151e with the suppression of password changing added that I purposely omitted. I think the suppression of changing of the password is too far, with a suitable local_vars.yml entry for iiab_admin_published_pwd the check should be suppressed anyway. The routine should be enforcing not using the default password in all cases, somebody will deploy with the stock password if it's that easy to skip the basic security idea of changing the password.

**Comment by holta** [comment]
I emphatically disagree:

Just 2 reasons among many:

1) `--fast` is not for the general public.  It is for **testers**.  And will very deliberately be promoted as such.
2) The detection & warning about iiab-admin's published password was made dramatically more prominent today (it's suddenly now the top message!) *and* it's suddenly now more colorful (red AND highlighted) — so testing folk can't avoid seeing it — with a ~5 second pause as 'apt update' does it's work. 

> with a suitable local_vars.yml entry for iiab_admin_published_pwd the check should be suppressed anyway.

This is a very small point, but FYI no:

- local_vars.yml is intentionally not checked.

- The key word here is "published"

- This is a hard-coded value, and very intentionally so (during the Very Earliest chicken+egg bootstrapping phase).

**Comment by holta** [comment]
Not that I'm a fan of segregation — but I believe everyone will benefit from admitting that these 3 demographics do have quite different assumptions & needs:

1. Implementers: `sudo iiab`
2. Testers: `sudo iiab -f`
3. Devs: `sudo iiab -F`

**Comment by holta** [comment]
FYI `--fast` can be renamed to `--risky` or `--danger` if absolutely necessary.

But more important that legalistic distractions, will be listening patiently to all 3 demographics over coming seasons, and what underlies their perceived desires...

**Comment by jvonau** [comment]
--fast seems ok, --mfabt may need the rename to "--risky" 
Still not sure why local_vars would not be consulted about the password in play for iiab-admin that is the whole point of local_vars.yml, local overrides from the defaults. I see you were forced to omit iiab_admin_user_password: "somestring" from local_vars.yml as a user defined field to break the automated iiab-admin creation with changed passwords with 'iiab_admin_published_pwd', didn't catch that sooner. Seems less than ideal, just reinforces why I use 'iiab_admin_user_install: False'.

**Comment by holta** [comment]
> --fast seems ok, --mfabt may need the rename to "--risky"

That's a solid suggestion.

As not everyone will understand the [Facebook reference](https://google.com/search?q=mive+fast+and+break+things).

**Comment by holta** [comment]
> --fast seems ok, --mfabt may need the rename to "--risky"

@jvonau's suggestion has been put into effect.

And as can be seen at [d.iiab.io](https://d.iiab.io) [*] only number 1. is prominently promoted, but all 3 are visible to those who are particularly curious:

1. [install.txt](http://d.iiab.io/install.txt) for sudo iiab
2. [fast.txt](http://d.iiab.io/fast.txt) for sudo iiab -f or --fast
3. [risky.txt](http://d.iiab.io/risky.txt) for sudo iiab -F or --risky

[*] same as [download.iiab.io](https://download.iiab.io), over HTTP/80 or HTTPS/443.

**Pull request merged**
